CREATE TABLE IF NOT EXISTS "users" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "username" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) DEFAULT NULL,
  "is_admin" BOOLEAN NOT NULL,
  "is_parent" BOOLEAN NOT NULL,
  "avatar" VARCHAR(255) DEFAULT NULL,
  "points" INT NOT NULL,
  "salt" VARCHAR(255) DEFAULT NULL,
  "password" VARCHAR(255) DEFAULT NULL,
  "pin" VARCHAR(255) DEFAULT NULL,
  "is_active" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP DEFAULT NULL,
  "updated_at" TIMESTAMP DEFAULT NULL
);
