CREATE TABLE IF NOT EXISTS "users" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "username" VARCHAR(15) NOT NULL UNIQUE,
  "email" VARCHAR(255) NOT NULL DEFAULT '',
  "is_admin" BOOLEAN DEFAULT FALSE,
  "is_parent" BOOLEAN DEFAULT FALSE,
  "avatar" VARCHAR(255) NOT NULL DEFAULT '',
  "points" INT DEFAULT 0,
  "password" VARCHAR(255) NOT NULL DEFAULT '',
  "pin" VARCHAR(255) NOT NULL DEFAULT '',
  "is_active" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
